(async () => {
  try {
  } catch (err) {
    console.error(err);
  }
})();
console.log('test-signin disabled: auth removed');
